---
roles:
- name: ctorgalson.macos_hostname
- name: gantsign.oh-my-zsh
- name: geerlingguy.docker
- name: grog.package
- name: ironicbadger.ansible_role_docker_compose_generator

collections:
  # community.general for osx_defaults
  - name: community.general 
  - name: geerlingguy.mac