---
roles:
- name: geerlingguy.docker
- name: ironicbadger.ansible_role_docker_compose_generator
- name: gantsign.oh-my-zsh
- name: ctorgalson.macos_hostname
- name: grog.package

collections:
  - name: geerlingguy.mac