---
- hosts: all
  tasks:
    - name: remove ubuntu motd spam
      become: true
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        # - 80-livepatch
        # - 95-hwe-eol
        - 10-help-text
      when: ansible_distribution == 'Ubuntu'

- hosts: winston
  roles:
    # Don't run it as root it will mess homebrew
    - role: ctorgalson.macos_hostname
    - role: oncleben31-mac-dev
      tags: ['homebrew']

- hosts: sombra
  roles:
    - role: gantsign.oh-my-zsh
    - role: geerlingguy.docker
    - role: oncleben31-sombra
    - role: ironicbadger.ansible_role_docker_compose_generator
      tags: ['compose']
