---
- hosts: macbookpro
  roles:
    - oncleben31-dev

- hosts: ubuntu
  roles:
    - role: geerlingguy.docker
    - role: oncleben31-ubuntu
    - role: ironicbadger.ansible_role_docker_compose_generator
