---

- name: Install dotfiles for oncleben31
  copy:
    src: "dotfiles/{{item}}"
    dest: "/Users/oncleben31/{{item}}"
    owner: "oncleben31"
    group: "staff"
  loop:
    - .gitconfig
  tags: ['dotfiles']

- name: Install Python versions
  include_tasks: python.yml

- name: Install pipx packages
  include_tasks: pipx.yml
  loop:
    "{{pipx_installed_packages_dev}}"
  loop_control: 
    loop_var: package
  tags: pipx


