- name: Install {{package.name}} with pipx
  block: 
    - name: Get pipx installed packages
      command: /usr/local/bin/pipx list --include-injected --json
      register: pipx_installed_packages
    
    - name: Install {{package.name}}
      command: /usr/local/bin/pipx install {{package.name}}
      register: output
      when: 
        - package.name not in (pipx_installed_packages.stdout | from_json).venvs.keys()

    - name: Inject some packages in {{package.name}}
      command: /usr/local/bin/pipx inject {{package.name}} {{item}}
      register: output
      when:
        - package.inject is defined
        - (package.name not in (pipx_installed_packages.stdout | from_json).venvs.keys()) or
          (item not in (pipx_installed_packages.stdout | from_json | community.general.json_query('venvs.' + package.name + '.metadata.injected_packages.*.package')))
      loop:
        "{{package.inject}}"
  become: yes
  become_user: oncleben31
  tags: pipx
  