---

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items: 
    - "{{ data_disks }}"

- name: mount disks
  mount:
    name: "{{ item.path }}"
    src: "{{ item.diskbyid }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - "{{ data_disks }}"
