---

- name: ensure hostname is set correctly
  hostname:
    name: "{{ hostname_sombra }}"

- name: disks
  include: disks.yml
  tags:
    - disks

- name: install dotfiles
  copy:
    src: "dotfiles/{{item}}"
    dest: "/home/{{main_username}}/{{item}}"
    owner: "{{main_username}}"
    group: "{{main_groupname}}"
  loop:
    - .oh-my-zsh/custom/aliases.zsh

- name: install oh my zsh custom plugins and theme
  include: oh-my-zsh-custom-install.yml
    user_item={{ item.username }}
    plugins_list={{ item.oh_my_zsh.plugins }}
    theme_item={{ item.oh_my_zsh.theme }}
  loop: "{{ users }}"
  tags: 
    - oh-my-zsh