---

- name: clone Oh My ZSH custom plugins for a user
  # ansible.builtin.debug:
  #   msg: "User is {{ user_item }}, plugin is {{ plugin }}, command is 'git clone {{ custom_plugins[plugin] }} {{ plugin }}"
  become: yes
  become_user: '{{ user_item }}'
  command: 'git clone  {{ custom_plugins[plugin] }} {{ plugin }}'
  args:
    chdir: '~{{ user_item }}/.oh-my-zsh/custom/plugins/'
    creates: '~{{ user_item }}/.oh-my-zsh/custom/plugins/{{plugin}}'
  with_items: "{{ plugins_list }}"
  when: plugin in custom_plugins.keys()
  loop_control:
    loop_var: plugin
  tags: 
    - oh-my-zsh
