---
# generic settings
main_username: oncleben31
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

ntp_timezone: "Europe/Paris"


# gantsign.oh-my-zsh
oh_my_zsh_theme: robbyrussell
oh_my_zsh_install: yes
oh_my_zsh_plugins:
  - git

users:
  - username: "{{ main_username }}"


# oncleben31-ubuntu
ubuntu_main_storage_path: /mnt/storage

data_disks:
  - { path: /mnt/storage, diskbyid: /dev/disk/by-id/scsi-1ATA_ST1000DM003-1ER162_Z4YB25V9-part1, fs: ext4, opts: defaults }


# ironicbadger.docker_compose_generator
appdata_path: /mnt/storage/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ main_username }}"


containers:
###
  - service_name: plex
    active: true
    image: plexinc/pms-docker
    network_mode: host
    volumes:
      - "{{ appdata_path }}/plex/config:/config"
      - /opt/appdata/plex/transcode:/transcode
      - "{{ ubuntu_main_storage_path }}:/data"
    include_global_env_vars: true
    restart: unless-stopped
###
