---

# ctorgalson.macos_hostname
mh_localhostname: winston
mh_computername: winston

# geerlingguy.mac.homebrew
homebrew_cask_appdir: /Applications

homebrew_cask_apps_default:
  - dropbox
  - google-chrome
  - discord
  - 1password
  - telegram
  - prusaslicer
  - ultimaker-cura
  - openscad

homebrew_installed_packages_default: []

homebrew_cask_apps_dev:
  - visual-studio-code
  - github

homebrew_installed_packages_dev:
  - ansible-lint
  - gh
  - git
  - nano
  - pipx
  - pre-commit
  - pyenv
  - rsync
  - ssh-copy-id

pipx_installed_packages_dev:
  - name: cookiecutter
  - name: poetry
  - name: nox
    inject: 
      - nox-poetry

VSC_extension_dev:
  - oncleben31: 
    visual_studio_code_extensions:
      - alefragnani.project-manager
      - ms-python.python
      - github.vscode-pull-request-github
      - keesschollaart.vscode-home-assistant
      - ms-vscode-remote.remote-containers


  


# Merge two categories of homebrew packages.
homebrew_cask_apps: "{{ homebrew_cask_apps_default + homebrew_cask_apps_dev }}"
homebrew_installed_packages: "{{ homebrew_installed_packages_default + homebrew_installed_packages_dev}}"

# Python versions to install with pyenv
pyenv_python_versions:
  - 3.9.9
  - 3.8.12
  - 3.10.0
