---

# ctorgalson.macos_hostname
mh_localhostname: winston
mh_computername: winston

# geerlingguy.mac.homebrew
homebrew_cask_appdir: /Applications

homebrew_cask_apps_default:
  - dropbox
  - google-chrome
  - discord
  - 1password
  - telegram
  - prusaslicer
  - ultimaker-cura

homebrew_installed_packages_default:
  - dockutil #paptch for updating Dock item for non-admin users

homebrew_cask_apps_dev:
  - visual-studio-code
  - github

homebrew_installed_packages_dev:
  - ansible-lint
  - gh
  - git
  - nano
  - pipx
  - pre-commit
  - pyenv
  - rsync
  - ssh-copy-id

# Merge two categories of homebrew packages.
homebrew_cask_apps: "{{ homebrew_cask_apps_default + homebrew_cask_apps_dev }}"
homebrew_installed_packages: "{{ homebrew_installed_packages_default + homebrew_installed_packages_dev}}"

# geerlingguy.mac.dock
dockitems_remove:
  - Mail
  - TV
  - Podcasts
  - Plans
  - Musique

dockitems_persist: []
  # - name: Google Chrome
  #   path: "/Applications/Google Chrome.app/"
  #   pos: 3
  # - name: Safari
  #   path: "/Applications/Safari.app/"
  #   pos: 4
  # - name: 1Paswword 7
  #   path: "/Applications/1Password 7.app/"
  #   pos: 5
  # - name: Visual Studio Code
  #   path: "/Applications/Visual Studio Code.app/"
  #   pos: 6
  # - name: Discord
  #   path: "/Applications/Discord.app/"
  #   pos: 7
  # - name: Telegram
  #   path: "/Applications/Telegram.app/"
  #   pos: 8
